import pandas as pd
from io import StringIO

# 假设这是你的 Markdown 表格原始代码
markdown_table = """

| 插件                                                     | Edge 下载                                                                                                                                                                                                                                                                | Chrome 下载                                                                                                                                                                                                              |
| :------------------------------------------------------- | :----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | :----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| Vue.js devtools                                          | [插件地址](https://microsoftedge.microsoft.com/addons/detail/vuejs-devtools/olofadcdnkkjdfgjcmjaadnlehnnihnl)                                                                                                                                                            | [插件地址](https://chrome.google.com/webstore/detail/vuejs-devtools/nhdogjmejiglipccpnnnanhbledajbpd)                                                                                                                    |
| Don't Close Window With Last Tab                         | [插件地址](https://microsoftedge.microsoft.com/addons/detail/dont-close-window-with-l/feebepaidmpgnkpngmeldoooofaacbhi)                                                                                                                                                  | [插件地址](https://chrome.google.com/webstore/detail/dont-close-window-with-la/dlnpfhfhmkiebpnlllpehlmklgdggbhn)                                                                                                         |
| Chrome 清理大师                                          | [插件地址](https://microsoftedge.microsoft.com/addons/detail/edge%E6%B8%85%E7%90%86%E5%A4%A7%E5%B8%88%EF%BC%9A%E4%B8%80%E9%94%AE%E6%B8%85%E7%90%86%E6%B5%8F%E8%A7%88%E5%99%A8%E5%9E%83%E5%9C%BE%EF%BC%8C%E8%AE%A9%E4%BD%A0%E7%9A%84edg/nlcebdoehkdiojeahkofcfnolkleembf) | [插件地址](https://chrome.google.com/webstore/detail/clean-master-the-best-chr/eagiakjmjnblliacokhcalebgnhellfi)                                                                                                         |
| uBlock Origin                                            | [插件地址](https://microsoftedge.microsoft.com/addons/detail/ublock-origin/odfafepnkmbhccpbejgmiehpchacaeak)                                                                                                                                                             | [插件地址](https://chrome.google.com/webstore/detail/ublock-origin/cjpalhdlnbpafiamejdnhcphjbkeiagm)                                                                                                                     |
| AdGuard 广告拦截器                                       | [插件地址](https://microsoftedge.microsoft.com/addons/detail/adguard-%E5%B9%BF%E5%91%8A%E6%8B%A6%E6%88%AA%E5%99%A8/pdffkfellgipmhklpdmokmckkkfcopbh)                                                                                                                     | [插件地址](https://chrome.google.com/webstore/detail/adguard-adblocker/bgnkhhnnamicmpeenaelnjfhikgbkllg)                                                                                                                 |
| Bitwarden - 免费密码管理器                               | [插件地址](https://microsoftedge.microsoft.com/addons/detail/bitwarden-%E5%AF%86%E7%A0%81%E7%AE%A1%E7%90%86%E5%99%A8/jbkfoedolllekgbhcbcoahefnbanhhlh)                                                                                                                   | [插件地址](https://chrome.google.com/webstore/detail/bitwarden-free-password-m/nngceckbapebfimnlniiiahkandclblb)                                                                                                         |
| Tampermonkey - 篡改猴                                    | [插件地址](https://microsoftedge.microsoft.com/addons/detail/%E7%AF%A1%E6%94%B9%E7%8C%B4/iikmkjmpaadaobahmlepeloendndfphd)                                                                                                                                               | [插件地址](https://chrome.google.com/webstore/detail/tampermonkey/dhdgffkkebhmkfjojejmpbldmpobfkfo)                                                                                                                      |
| 京价保 - 京东价保助手                                    | [插件地址](https://microsoftedge.microsoft.com/addons/detail/%E4%BA%AC%E4%BB%B7%E4%BF%9D-%E4%BA%AC%E4%B8%9C%E4%BB%B7%E4%BF%9D%E5%8A%A9%E6%89%8B/ljdjkkjiognkghfjndoddoplekppngge)                                                                                        | [插件地址](https://chrome.google.com/webstore/detail/%E4%BA%AC%E4%BB%B7%E4%BF%9D-%E4%BA%AC%E4%B8%9C%E4%BB%B7%E4%BF%9D%E5%8A%A9%E6%89%8B/gfgkebiommjpiaomalcbfefimhhanlfd)                                                |
| 喵喵折+                                                  | [插件地址](https://microsoftedge.microsoft.com/addons/detail/%E5%96%B5%E5%96%B5%E6%8A%98/pbmmogmpniaejfceedmjhdobmenbggoo)                                                                                                                                               | [插件地址](https://chrome.google.com/webstore/detail/%E5%96%B5%E5%96%B5%E6%8A%98%20/ekbmhggedfdlajiikminikhcjffbleac)                                                                                                    |
| 稀土掘金                                                 | [插件地址](https://microsoftedge.microsoft.com/addons/detail/%E7%A8%80%E5%9C%9F%E6%8E%98%E9%87%91/iblloeofmdhfkbkpjkkombjngddeocjk)                                                                                                                                      | [插件地址](https://chrome.google.com/webstore/detail/%E7%A8%80%E5%9C%9F%E6%8E%98%E9%87%91/lecdifefmmfjnjjinhaennhdlmcaeeeb)                                                                                              |
| ACG助手 - 专为哔哩哔哩(bilibili)定制，可视频下载消息推送 | [插件地址](https://microsoftedge.microsoft.com/addons/detail/acg%E5%8A%A9%E6%89%8B-%E4%B8%93%E4%B8%BA%E5%93%94%E5%93%A9%E5%93%94%E5%93%A9bilibili%E5%AE%9A/fcfebhekhbkhjjimonjmbgmkbclheaoh)                                                                             | [插件地址](https://chrome.google.com/webstore/detail/%E5%93%94%E5%93%A9%E5%93%94%E5%93%A9%E5%8A%A9%E6%89%8B%EF%BC%9Abilibilicom-%E7%BB%BC%E5%90%88%E8%BE%85%E5%8A%A9%E6%89%A9%E5%B1%95/kpbnombpnpcffllnianjibmpadjolanh) |
| 迅雷下载支持                                             | [插件地址](https://microsoftedge.microsoft.com/addons/detail/%E8%BF%85%E9%9B%B7%E4%B8%8B%E8%BD%BD%E6%94%AF%E6%8C%81/popomkonnjgcdagdhgcpcekbdeoibglc)                                                                                                                    | [插件地址](https://chrome.google.com/webstore/detail/%E8%BF%85%E9%9B%B7%E4%B8%8B%E8%BD%BD%E6%94%AF%E6%8C%81/ncennffkjdiamlpmcbajkmaiiiddgioo)                                                                            |

"""

# 将 Markdown 表格转换为 DataFrame
df = pd.read_csv(StringIO(markdown_table), sep="|", skipinitialspace=True, header=0, index_col=0)
# df = df.drop(df.columns[-1], axis=1)
df = df[~df.apply(lambda row: row.astype(str).str.contains("---").any(), axis=1)]

# 将 DataFrame 转换为 CSV
csv_output = df.to_csv(index=False)
print(csv_output)
